version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: unless-stopped
    networks:
      - shared-network

networks:
  shared-network:
    external: true
