version: '3.8'

services:
  frontend:
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ~/certbot/www:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    restart: always
    networks:
      - mynetwork

networks:
  mynetwork:
